In [3]:
import tabula
import pandas as pd
import requests 
import json
from pandas.io.json import json_normalize
import numpy as np

### pobieranie tabel

In [270]:
# Read pdf into DataFrame
#https://stackoverflow.com/questions/45457054/tabula-extract-tables-by-area-coordinates
#pobieranie danych dla diecezji
#https://docs.google.com/spreadsheets/d/1WHCrTZX2WJeYStcG58wh6y9Q58bwhGRG92iLxz4Paek/edit#gid=752560630
df = tabula.read_pdf("dane_pdf/analiza_elektoratu/2019/K_038_17.PDF",
                     multiple_tables=True, 
                     pages=[9],
                     #stream = True
                     guess = True,  
                     #pandas_options={'header':True},
                     #area=(20, 40, 695, 589),
                     spreadsheet=True
                    )
name = '2017_04'

In [273]:
df[0]

,0,1,2,3,4,5,6
0,Gdyby mógł Pan (mogła Pani)\rgłosować na kandy...,Potencjalne elektoraty ugrupowań politycznych,NaN,NaN,NaN,NaN,NaN
1,NaN,PiS\r(wraz SP\ri PR)\rN=522,PO\rN=241,Nowoczesna\rN=114,Kukiz’15\rN=115,SLD\rN=64,PSL\rN=55
2,NaN,w procentach,NaN,NaN,NaN,NaN,NaN
3,Prawo i Sprawiedliwość\r(wraz z Solidarną Pols...,-,4,2,28,6,5
4,Platforma Obywatelska RP,5,-,51,10,25,18
5,Nowoczesna Ryszarda Petru,1,38,-,6,15,11
6,Kukiz’15,40,6,1,-,8,13
7,Sojusz Lewicy Demokratycznej,3,13,12,2,-,9
8,Polskie Stronnictwo Ludowe,8,12,6,2,8,-
9,Partia Razem,0,4,5,2,8,9
10,Wolność,1,0,4,14,2,0
11,Inna partia*,0,0,1,3,1,4
12,Nie mam takiej partii,36,20,15,32,22,25
13,Trudno powiedzieć,6,4,3,2,6,5

In [275]:
df_clean = df[0].drop([0,2])
#df_clean.iloc[0,5] = df_clean.iloc[0,5].replace('r','')
list_col = [ str(c).split('\rN')[0] for c in df_clean.iloc[0].to_list()]
list_col = [ str(c).replace('\r', '') for c in list_col]
list_col

['nan', 'PiS(wraz SPi PR)', 'PO', 'Nowoczesna', 'Kukiz’15', 'SLD', 'PSL']

In [276]:
df_clean.iloc[0]
columns = df_clean.iloc[0]
list_col[0] = 'Party'
df_clean.columns = list_col
df_clean = df_clean.drop([1])

In [280]:
df_clean['Party'] = [str(c).replace('\r', '') for c in df_clean['Party'].to_list()]

In [281]:
df_clean

,Party,PiS(wraz SPi PR),PO,Nowoczesna,Kukiz’15,SLD,PSL
3,Prawo i Sprawiedliwość(wraz z Solidarną Polską...,-,4,2,28,6,5
4,Platforma Obywatelska RP,5,-,51,10,25,18
5,Nowoczesna Ryszarda Petru,1,38,-,6,15,11
6,Kukiz’15,40,6,1,-,8,13
7,Sojusz Lewicy Demokratycznej,3,13,12,2,-,9
8,Polskie Stronnictwo Ludowe,8,12,6,2,8,-
9,Partia Razem,0,4,5,2,8,9
10,Wolność,1,0,4,14,2,0
11,Inna partia*,0,0,1,3,1,4
12,Nie mam takiej partii,36,20,15,32,22,25
13,Trudno powiedzieć,6,4,3,2,6,5

In [282]:
df_clean.to_csv('dane_pdf/analiza_elektoratu/'+name+'.csv', index = False, header=True)

# Dane - pytanie elektoratów

In [140]:
df = tabula.read_pdf("dane_pdf/charaktetyryka_pogladow/pdf/K_124_19.PDF",
                     multiple_tables=True, 
                     pages=[21,22],
                     #stream = True
                     guess = True,  
                     #pandas_options={'header':True},
                     #area=(20, 40, 695, 589),
                     spreadsheet=True
                    )

In [129]:
df_names = df[0]

## Points

In [96]:
for i in range(len(df)):
    df[i] = df[i].dropna().reset_index()
    df[i]
catg = 'points'

## Percent

In [111]:
for i in range(len(df)):
    df[i] = df[i].drop(0)
    df[i] = df[i].drop(2)
    df[i]
catg = 'percent'

KeyError: '[2] not found in axis'

In [131]:
result = pd.concat([df_names,df[0],df[1]]).reset_index()
del result['index']
try:
    del result['level_0']
except:
    pass
result

,0,1,2,3
0,KW Prawo\ri Spra-\rwiedliwość,KKW Koalicja\rObywatelska\rPO .N IPL\rZieloni,KW Sojusz\rLewicy Demo-\rkratycznej,KW Polskie\rStronnictwo\rLudowe
1,"1,83","2,18","2,13","2,06"
2,"2,84","3,62","3,29","3,00"
3,"4,10","4,35","4,44","4,20"
4,"6,03","4,57","4,55","4,91"
5,"4,06","5,04","4,88","4,50"
6,"5,31","3,35","2,50","4,09"
7,"5,37","2,83","1,97","3,57"
8,"6,11","3,38","2,26","4,64"
9,"3,70","1,84","1,42","2,10"
10,"4,64","2,40","2,65","3,34"
11,"6,27","4,07","4,46","5,19"
12,"6,44","4,24","4,14","5,14"
13,"4,16","3,84","4,17","4,49"
14,"3,17","1,86","1,92","1,99"

In [132]:
result = result.drop_duplicates(subset=None, keep='first', inplace=False)

In [133]:
result = result.apply(lambda x: x.str.replace(',','.'))

In [134]:
result[0] = [q.replace('\n',' ').replace('\r','') if type(q) == str else 'Question' for q in result[0]]
result.loc[0] = [q.replace('\n',' ').replace('\r','') if type(q) == str else 'Question' for q in result.loc[0]]

In [135]:
result

,0,1,2,3
0,KW Prawoi Spra-wiedliwość,KKW KoalicjaObywatelskaPO .N IPLZieloni,KW SojuszLewicy Demo-kratycznej,KW PolskieStronnictwoLudowe
1,1.83,2.18,2.13,2.06
2,2.84,3.62,3.29,3.00
3,4.10,4.35,4.44,4.20
4,6.03,4.57,4.55,4.91
5,4.06,5.04,4.88,4.50
6,5.31,3.35,2.50,4.09
7,5.37,2.83,1.97,3.57
8,6.11,3.38,2.26,4.64
9,3.70,1.84,1.42,2.10
10,4.64,2.40,2.65,3.34
11,6.27,4.07,4.46,5.19
12,6.44,4.24,4.14,5.14
13,4.16,3.84,4.17,4.49
14,3.17,1.86,1.92,1.99

In [137]:
result.to_csv('dane_pdf/charaktetyryka_pogladow/2019_'+catg+'.csv', index = False, header=False)

In [136]:
catg = 'points'